name: mutants

on:
  schedule:
    - cron: '3 3 * * *'
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/mutants-run.yaml
    permissions:
      contents: read
      issues: write
    with:
      sha: ${{ github.sha }}
